#!/usr/bin/env python3
"""Generate LuxeRoutes offer-card HTML from markdown front matter.

The script intentionally uses only the Python standard library so the static site can
be maintained without a package manager. It reads published accommodation offers
from content/offers/** and writes a reusable HTML snippet for offers.html.
"""
from __future__ import annotations

import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT_ROOT = ROOT / "content" / "offers"
OUTPUT = CONTENT_ROOT / "_generated" / "offers-cards.html"

LIST_KEYS = {"region", "options", "search_terms"}


def parse_value(raw: str):
    value = raw.strip()
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    if value in {"true", "false"}:
        return value == "true"
    return value


def read_front_matter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---", text, re.S)
    if not match:
        return {}

    data: dict[str, object] = {}
    current_key: str | None = None
    for raw_line in match.group(1).splitlines():
        if not raw_line.strip():
            continue
        if raw_line.startswith("  - ") and current_key:
            data.setdefault(current_key, [])
            assert isinstance(data[current_key], list)
            data[current_key].append(parse_value(raw_line[4:]))
            continue
        if ":" not in raw_line:
            continue
        key, raw_value = raw_line.split(":", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        current_key = key
        if key in LIST_KEYS and not raw_value:
            data[key] = []
        else:
            data[key] = parse_value(raw_value)
    return data


def esc(value: object) -> str:
    return html.escape(str(value or ""), quote=True)


def as_tokens(value: object) -> str:
    if isinstance(value, list):
        return " ".join(str(item) for item in value)
    return str(value or "")


def render_card(offer: dict) -> str:
    title = esc(offer.get("title"))
    country = esc(offer.get("country"))
    region = esc(as_tokens(offer.get("region")))
    stay_type = esc(offer.get("type"))
    options = esc(as_tokens(offer.get("options")))
    image = esc(offer.get("image"))
    image_alt = esc(offer.get("image_alt"))
    badge = esc(offer.get("badge"))
    guests = esc(offer.get("guests"))
    price_note = esc(offer.get("price_note"))
    cta_label = esc(offer.get("cta_label") or "Request stay")
    short_description = esc(offer.get('short_description', '').strip() or 'Curated stay concept prepared for a private LuxeRoutes brief.')

    return f'''          <article class="offer-card" data-offer-card data-country="{country}" data-region="{region}" data-type="{stay_type}" data-options="{options}">
            <div class="offer-media">
              <img src="{image}" alt="{image_alt}" loading="lazy" decoding="async" width="900" height="600" />
              <span>{badge}</span>
            </div>
            <div class="offer-body">
              <h3>{title}</h3>
              <p>{short_description}</p>
              <div class="offer-meta"><span>{guests}</span><span>{price_note}</span></div>
            </div>
            <div class="offer-footer"><a class="text-link" href="plan-trip.html">{cta_label}</a></div>
          </article>'''


def main() -> None:
    offers = []
    for path in sorted(CONTENT_ROOT.glob("*/accommodation/**/*.md")):
        data = read_front_matter(path)
        if data.get("status") != "published":
            continue
        if data.get("content_kind") != "accommodation":
            continue
        if not data.get("title") or not data.get("image"):
            continue

        body = path.read_text(encoding="utf-8").split("---", 2)[-1]
        short_match = re.search(r"## Short description\n\n(.+?)(?:\n\n##|\Z)", body, re.S)
        if short_match:
            data["short_description"] = " ".join(short_match.group(1).strip().split())
        offers.append(data)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "<!-- Generated by scripts/generate-offers.py. Copy into offers.html or wire into your deploy step. -->\n"
        + "\n\n".join(render_card(offer) for offer in offers)
        + "\n",
        encoding="utf-8",
    )
    print(f"Generated {len(offers)} offer cards at {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
